---
abstract: 'Subprocess manager for Gearman workers in a'
author:
  - 'Adam Thomason, <athomason@sixapart.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gearman-WorkerSpawner
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Danga::Socket: 1.59
  Gearman::Client: 1.09
  Gearman::Client::Async: 0.94
  Gearman::Server: 1.09
  Storable: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.02
