---
abstract: 'Subprocess manager for Gearman workers in a'
author:
  - 'Adam Thomason, <athomason@sixapart.com>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Gearman-WorkerSpawner
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Danga::Socket: 1.59
  Gearman::Client: 1.09
  Gearman::Client::Async: 0.94
  Gearman::Server: 1.09
  Storable: 0
version: 1.01
